#os with Env /base images
FROM openjdk:17-jdk-alpine

#working directory
WORKDIR /app

#code
COPY src/Main.java /app/Main.java

#libraries
RUN javac Main.java

#run
CMD ["java","Main"]


the link for the java app is https://github.com/LondheShubham153/simple-java-docker.git
