FROM ubuntu:22.04

#CMD ["echo", "Hello from CMD"]

#build this image
#run container using ----> docker run cmdtest:latest      //it will show echo output and tuned off
# docker run cmdtest:latest echo "CMD overwrite ho jao"   //it means we can overwrite CMD on runtime
#----------------------------#

ENTRYPOINT ["echo", "Hello from entrypoint"]
#again build ,, again run the container with run time argument

#it will append the output